export const META_KEY = 'NGXS_META';
export const META_OPTIONS_KEY = 'NGXS_OPTIONS_META';
export const STATE_ACTIONS = 'STATE_ACTIONS';
export const STATE_GETTERS = 'STATE_GETTERS';
export const STATE_GETTERS_PATHS = 'STATE_GETTERS_PATHS';
export const STATE_STORE = 'STATE_STORE';
export const FULL_STATE_KEY = 'FULL_STATE_KEY';
export const FULL_STATE_FOR_WINDOW = 'FULL_STATE_FOR_WINDOW';
